// Angular_React_Vue/Day8/Assignments/NgForms/Source/src/app/app.component.ts
import { Component } from '@angular/core';
import { FormGroup,FormControl,FormArray,FormBuilder,Validators } from '@angular/forms';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'source';
  newarr:Array<any>= []
  myForm : FormGroup
  constructor(){
  this.myForm = new FormGroup({
   Name:new FormGroup({
     firstname: new FormControl(null,Validators.required),
     middlename: new FormControl(null,Validators.required),
     lastname : new FormControl(null,Validators.required)
   }),  
   DOB:new FormControl(),
   Place_of_birth: new FormControl(),
   First_language:new FormControl(),
   Address:new FormGroup(
   {
    city: new FormControl(),
    state: new FormControl(),
    country: new FormControl(),
    pin: new FormControl()
   }),
   mother:new FormGroup({
    firstname: new FormControl(),
    middlename: new FormControl(),
    lastname : new FormControl()        
   }),
   Email: new FormControl(null,[Validators.email,Validators.required]),
   Education_Qualification: new FormControl(),
   Profession: new FormControl(),
   Designation: new FormControl(),
   Phone:new FormControl(),
   Emergency_List: new FormArray([new FormControl(""),new FormControl("")]),
   Relation:new FormControl(),
   Reference_Details: new FormArray([new FormControl(""),new FormControl("")]),
  })
  }
 
  get referencechild(){
    return this.myForm.get("Reference_Details") as FormArray 
  }
   
  get emergencychild(){
    return this.myForm.get("Emergency_List") as FormArray
  }
 
  submitdata(){
   var dm = this.newarr.push(this.myForm.value)
    var secondarr = this.newarr.map((e)=>{
    })
    }


  get fname(){
    return this.myForm.get("Name.firstname")
  }
  get mname(){
    return this.myForm.get("Name.middlename")
  }
  get lname(){
    return this.myForm.get("Name.lastname")
  }
  get email(){
    return this.myForm.get('Email')
  }

//   Name:new FormGroup({
//     firstname: new FormControl(),
//     middlename: new FormControl(),
//     lastname : new FormControl()
//   }),  
//   DOB:new FormControl(),
//   Place_of_birth: new FormControl(),
//   First_language:new FormControl(),
//   Address:new FormGroup(
//   {
//    city: new FormControl(),
//    state: new FormControl(),
//    country: new FormControl(),
//    pin: new FormControl()
//   }),
//   mother:new FormGroup({
//    firstname: new FormControl(),
//    middlename: new FormControl(),
//    lastname : new FormControl()        
//   }),
//   Email: new FormControl(),
//   Education_Qualification: new FormControl(),
//   Profession: new FormControl(),
//   Designation: new FormControl(),
//   Phone:new FormControl(),
//   Emergency_List: new FormArray([new FormControl(""),new FormControl("")]),
//   Relation:new FormControl(),
//   Reference_Details: new FormArray([new FormControl(""),new FormControl("")]),
//  })
//  }
}

<div id="my">
<div class="row mx-auto">
<div class="col-sm-12 first container">
<h2 id="h3" class="text-center text-primary">Student Form</h2>
<form action="" [formGroup]="myForm" (ngSubmit)="submitdata()">
  <div class="row">
    <div class="col-sm-6">
<div formGroupName="Name">
<label for="fname">First Name:</label>
<input type="text" formControlName="firstname"><small *ngIf="fname?.invalid">firstname is Required</small><br><br>
<label for="fname">Middle Name:</label>
<input type="text" formControlName = "middlename"><small *ngIf="mname?.invalid">firstname is Required</small><br><br>
<label for="fname">Last Name:</label>
<input type="text" formControlName = "lastname"><small *ngIf="lname?.invalid">firstname is Required</small>
</div><br>
<label for="Doj">Date of joining:</label>
<input type="date" formControlName = "DOB"><br><br>
<label for="Place_of_birth">Place of birth:</label>
<input type="text" formControlName = "Place_of_birth"><br><br>
<label for="First_language">First language:</label>
<input type="text" formControlName = "First_language"><br><br>
<div formGroupName="Address">
 <label for="city">City</label>
 <select formControlName="city">
  <option value="vadodara">Vadodara</option>
  <option value="surat">surat</option>
 </select>    <!--small *ngIf="city?.invalid">city is Required</small-->
 <br><br>
 <label for="state">State</label>
 <select formControlName="state">
   <option value="gujarat">Gujarat</option>
   <option value="Maharashtra">Maharashtra</option>
   <option value="Rajasthan">Rajasthan</option>
 </select> <!--small *ngIf="state?.invalid">state is Required</small-->
 <br><br>
 <label for="country">Country</label>
 <select formControlName="country">
   <option value="India">India</option>
   <option value="India">Pakistan</option>
   <option value="India">Srilanka</option>
 </select>     <!--small *ngIf="city?.invalid">country is Required</small-->
 <br><br>
</div>  

<div formGroupName="mother">
 <label for="firstname">Mother-Firstname</label>
 <input type="text" formControlName="firstname"><br><br>
 <label for="middlename">Mother-Middlename</label>
 <input type="text" formControlName="middlename"><br><br>
 <label for="lastname">Mother-Lastname</label>
 <input type="text" formControlName="lastname"><br><br>
</div>
</div>
<div class="col-sm-6">
<label for="Email">Email</label>
<input type="email" formControlName="Email"><small *ngIf="email?.invalid">Email Id contains @</small><br><br>
<label for="Education_Qualification">Education_Qua</label>
<input type="text" formControlName="Education_Qualification"><br><br>
<label for="Profession">Profession</label>
<input type="text" formControlName="Profession"><br><br>
<label for="Designation">Designation</label>
<input type="text" formControlName="Designation"><br><br>
<label for="Phone">Phone</label>
<input type="text" formControlName="Phone"><br><br>
<div formArrayName="Emergency_List">
<div *ngFor="let d of emergencychild.controls;let i=index">
<label for="Emergency_List">Emergency Contact</label>
<input type="text" placeholder="enter number" [formControlName]="i"><br><br>
</div>
</div>
<label for="Relation">Relation</label>
<input type="text" formControlName="Relation"><br><br>
<div formArrayName="Reference_Details">
  <div *ngFor="let s of referencechild.controls;let b=index">  
  <label for="Reference_Details">Reference_Details</label>
  <input type="text" placeholder="enter referances" [formControlName]="b"><br><br>
  </div>
</div>
<button [disabled]="myForm.invalid" class="mb-5 btn btn-danger">Submit</button>
</div>
</div>
</form>
<div>
 <div class="row"> 
<div class="col-sm-12 second">
<h2 class="text-center text-success">Show Student Data</h2>
<div id="tableid">
 <table class="table table-striped" aria-describedby="table">
  <tr>
   <th>FName</th>
   <th>MName</th>
   <th>LName</th>
   <th>DOB</th>
   <th>BirthPlace</th>
   <th>First-lang</th>
   <th>City</th>
   <th>State</th>
   <th>Country</th>
   <th>Pin</th>
   <th>M-Firstname</th>
   <th>M-Middlename</th>
   <th>M-Lastname</th>
   <th>Email</th>
   <th>Edu_Qua</th>
   <th>Profession</th>
   <th>Designation</th>
   <th>Phone</th>
   <th>EmergencyList</th>
   <th>Relation</th>
   <th>RefDetails</th>
  </tr>
  <tr *ngFor="let myarr of newarr">  
   <td>{{myarr.Name.firstname}}</td>
   <td>{{myarr.Name.middlename}}</td>
   <td>{{myarr.Name.lastname}}</td>
   <td>{{myarr.DOB}}</td>
   <td>{{myarr.Place_of_birth}}</td>
   <td>{{myarr.First_language}}</td>
   <td>{{myarr.Address.city}}</td>
   <td>{{myarr.Address.state}}</td>
   <td>{{myarr.Address.country}}</td>
   <td>{{myarr.Address.pin}}</td>
   <td>{{myarr.mother.firstname}}</td>
   <td>{{myarr.mother.middlename}}</td>
   <td>{{myarr.mother.lastname}}</td>
   <td>{{myarr.Email}}</td>
   <td>{{myarr.Education_Qualification}}</td>
   <td>{{myarr.Profession}}</td>
   <td>{{myarr.Designation}}</td>
   <td>{{myarr.Phone}}</td>
   <td>{{myarr.Emergency_List}}</td>
   <td>{{myarr.Relation}}</td>
   <td>{{myarr.Reference_Details}}</td>
  </tr>
 </table>
</div>
</div>
</div>
</div>

// Angular_React_Vue/Day9/Assignments/VueForms/Source/src/App.vue
<template>
  <div>
    <h3 class="text-center">Student Registration Form</h3>
    <form @submit.prevent="submitdata" class="admissionform">
      <label for="firstName"
        >First Name : <span class="required">*</span></label
      >
      <input
        id="firstName"
        class="w-100"
        type="text"
        v-model="student.Name.firstName"
        @blur="v$.student.Name.firstName.$touch"
      />
      <span class="text-danger" v-if="v$.student.Name.firstName.$error">
        <small>First Name is required</small>
      </span>
      <br /><br />
      <label for="mname">Middle Name :<span class="required">*</span></label>
      <input
        id="mname"
        class="w-100"
        type="text"
        v-model="student.Name.middleName"
        @blur="v$.student.Name.middleName.$touch"
      />
      <span class="text-danger" v-if="v$.student.Name.middleName.$error">
        <small>Middle Name is required</small>
      </span>
      <br /><br />
      <label for="lname">Last Name :<span class="required">*</span></label>
      <input
        id="lname"
        class="w-100"
        type="text"
        v-model="student.Name.lastName"
        @blur="v$.student.Name.lastName.$touch"
      />
      <span class="text-danger" v-if="v$.student.Name.lastName.$error">
        <small>Last Name is required</small>
      </span>
      <br /><br />
      <label for="dob">Date of Birth : <span class="required">*</span> </label>
      <input
        id="dob"
        class="w-100"
        type="date"
        v-model="student.DOB"
        @blur="v$.student.DOB.$touch"
      />
      <span class="text-danger" v-if="v$.student.DOB.$error">
        <small>Date of Birth is required</small>
      </span>
      <br /><br />
      <label for="pob">Place of Birth : </label>
      <input
        id="pob"
        class="w-100"
        type="text"
        v-model="student.place_of_birth"
      />
      <br /><br />
      <label for="flang">First Language : </label>
      <input
        id="flang"
        class="w-100"
        type="text"
        v-model="student.first_language"
      />
      <br /><br />
      <label for="city">City : </label>
      <input
        id="city"
        class="w-100"
        type="text"
        v-model="student.Address.City"
      />
      <br /><br />
      <label for="state">State : </label>
      <input
        id="state"
        class="w-100"
        type="text"
        v-model="student.Address.State"
      />
      <br /><br />
      <label for="country">Country : </label>
      <input
        id="country"
        class="w-100"
        type="text"
        v-model="student.Address.Country"
      />
      <br /><br />
      <label for="pin">Pin Code: </label>
      <input
        id="pin"
        class="w-100"
        type="text"
        v-model="student.Address.Pin"
      /><br />
      <br /><br />
      <h3>Fathers details</h3>
      <label for="ffirstname"
        >First Name : <span class="required">*</span></label
      >
      <input
        id="ffirstname"
        class="w-100"
        type="text"
        v-model="student.FathersDetails.FatherName.ffirstname"
        @blur="v$.student.FathersDetails.FatherName.ffirstname.$touch"
      />
      <span
        class="text-danger"
        v-if="v$.student.FathersDetails.FatherName.ffirstname.$error"
      >
        <small>Fathers Name is required</small>
      </span>
      <br /><br />
      <label for="fmiddlename">Middle Name : </label>
      <input
        id="fmiddlename"
        class="w-100"
        type="text"
        v-model="student.FathersDetails.FatherName.fmiddlename"
      />
      <br /><br />
      <label for="flastname">Last Name : </label>
      <input
        id="flastname"
        class="w-100"
        type="text"
        v-model="student.FathersDetails.FatherName.flastname"
      />
      <br /><br />
      <label for="femail">Email : </label>
      <input
        id="femail"
        class="w-100"
        type="email"
        v-model="student.FathersDetails.femail"
        @blur="v$.student.FathersDetails.femail.$touch"
      />
      <span class="text-danger" v-if="v$.student.FathersDetails.femail.$error">
        <small>Enter Valid Email</small>
      </span>
      <br /><br />
      <label for="feq">Education Qualification : </label>
      <textarea
        id="feq"
        class="w-100"
        cols="25"
        rows="3"
        v-model="student.FathersDetails.feq"
      ></textarea>
      <br /><br />
      <label for="fprof">Profession: </label>
      <input
        id="fprof"
        class="w-100"
        type="text"
        v-model="student.FathersDetails.fprof"
      />
      <br /><br />
      <label for="fdesg">Designation: </label>
      <input
        id="fdesg"
        class="w-100"
        type="text"
        v-model="student.FathersDetails.fdesg"
      />
      <br /><br />
      <label for="fphone">Phone: <span class="required">*</span></label>
      <input
        id="fphone"
        class="w-100"
        type="text"
        v-model="student.FathersDetails.fphone"
        @blur="v$.student.FathersDetails.fphone.$touch"
      />
      <span class="text-danger" v-if="v$.student.FathersDetails.fphone.$error">
        <small>Enter Valid Number</small>
      </span>
      <br /><br />

      <h3>Mothers details</h3>
      <label for="mfirstname"
        >First Name : <span class="required">*</span></label
      >
      <input
        id="mfirstname"
        class="w-100"
        type="text"
        v-model="student.MothersDetails.MotherName.mfirstname"
        @blur="v$.student.MothersDetails.MotherName.mfirstname.$touch"
      />
      <span
        class="text-danger"
        v-if="v$.student.MothersDetails.MotherName.mfirstname.$error"
      >
        <small>Mother's Name is required</small>
      </span>
      <br /><br />
      <label for="mmiddlename">Middle Name : </label>
      <input
        id="mmiddlename"
        class="w-100"
        type="text"
        v-model="student.MothersDetails.MotherName.mmiddlename"
      />
      <br /><br />
      <label for="mlastname">Last Name : </label>
      <input
        id="mlastname"
        class="w-100"
        type="text"
        v-model="student.MothersDetails.MotherName.mlastname"
      />
      <br /><br />
      <label for="memail">Email : </label>
      <input
        id="memail"
        class="w-100"
        type="email"
        v-model="student.MothersDetails.memail"
        @blur="v$.student.MothersDetails.memail.$touch"
      />
      <span class="text-danger" v-if="v$.student.MothersDetails.memail.$error">
        <small>Enter Valid Email</small>
      </span>
      <br /><br />
      <label for="meq">Education Qualification : </label>
      <textarea
        id="meq"
        class="w-100"
        cols="25"
        rows="3"
        v-model="student.MothersDetails.meq"
      ></textarea>
      <br /><br />
      <label for="mprof">Profession: </label>
      <input
        id="mprof"
        class="w-100"
        type="text"
        v-model="student.MothersDetails.mprof"
      />
      <br /><br />
      <label for="mdesg">Designation: </label>
      <input
        id="mdesg"
        class="w-100"
        type="text"
        v-model="student.MothersDetails.mdesg"
      />
      <br /><br />
      <label for="mphone">Phone: <span class="required">*</span></label>
      <input
        id="mphone"
        class="w-100"
        type="text"
        v-model="student.MothersDetails.mphone"
        @blur="v$.student.MothersDetails.mphone.$touch"
      />
      <span class="text-danger" v-if="v$.student.MothersDetails.mphone.$error">
        <small>Enter Valid Number</small>
      </span>

      <br /><br />
      <label for="enumber">Emergency Contact : </label> <br />
      <br />
      <div v-for="num in student.enumber" :key="num.relation">
        <label for="relation">Relation</label>
        <select
          name="relation"
          id="relation"
          v-model="num.relation"
          class="w-25"
        >
          <option value="">Select</option>
          <option value="Father">Father</option>
          <option value="Mother">Mother</option>
          <option value="Brother">Brother</option>
          <option value="Sister">Sister</option>
          <option value="Other">Other</option>
        </select>

        <label for="number">Number :</label>
        <input type="text" v-model="num.number" />
      </div>
      <button @click.prevent="addenumber">ADD</button>

      <br /><br />
      <label for="refthrough">Reference Through : </label>
      <select id="refthrough" class="w-100" v-model="student.refthrough">
        <option value="">Select</option>
        <option value="Online">Online</option>
        <option value="AdmissionCell">Admission Cell</option>
        <option value="Template">Template</option>
      </select>
      <br /><br />
      <label for="address">Address : </label>
      <textarea
        id="address"
        class="w-100"
        cols="25"
        rows="3"
        v-model="student.address"
      ></textarea>
      <br /><br />
      <label for="contact">Contact : <span class="required">*</span></label>
      <input
        id="contact"
        class="w-100"
        type="text"
        v-model="student.contact"
        @blur="v$.student.contact.$touch"
      />
      <span class="text-danger" v-if="v$.student.contact.$error">
        <small>Number is invalid</small>
      </span>
      <br /><br />
      <input type="submit" value="Submit" />
      <input type="reset" value="Reset" />
    </form>

    <table class="table table-responsive table-bordered">
      <caption></caption>
      <thead>
        <tr>
          <th rowspan="2" scope="">FirstName</th>
          <th rowspan="2" scope="">MiddleName</th>
          <th rowspan="2" scope="">LastName</th>
          <th rowspan="2" scope="">DOB</th>
          <th rowspan="2" scope="">Place of Birth</th>
          <th rowspan="2" scope="">First Language</th>
          <th colspan="4" scope="">Address</th>
          <th colspan="8" scope="">Fathers Details</th>
          <th colspan="8" scope="">Mothers Details</th>
          <th colspan="2" scope="">Emergency Contact</th>
          <th rowspan="2" scope="">Reference Through</th>
          <th rowspan="2" scope="">Address</th>
          <th rowspan="2" scope="">Contact</th>
        </tr>
        <tr>
          <th scope="">City</th>
          <th scope="">State</th>
          <th scope="">Country</th>
          <th scope="">Pin</th>
          <th scope="">firstName</th>
          <th scope="">middleName</th>
          <th scope="">lastName</th>
          <th scope="">Email</th>
          <th scope="">Education_q</th>
          <th scope="">profession</th>
          <th scope="">designation</th>
          <th scope="">phone</th>
          <th scope="">firstName</th>
          <th scope="">middleName</th>
          <th scope="">lastName</th>
          <th scope="">Email</th>
          <th scope="">Education_q</th>
          <th scope="">profession</th>
          <th scope="">designation</th>
          <th scope="">phone</th>
          <th scope="">Relation</th>
          <th scope="">Number</th>
        </tr>
      </thead>
      <tbody v-for="item in allentries" :key="item.Name.firstName">
        <tr>
          <td>{{ item.Name.firstName }}</td>
          <td>{{ item.Name.middleName }}</td>
          <td>{{ item.Name.lastName }}</td>
          <td>{{ item.DOB }}</td>
          <td>{{ item.place_of_birth }}</td>
          <td>{{ item.first_language }}</td>
          <td>{{ item.Address.City }}</td>
          <td>{{ item.Address.State }}</td>
          <td>{{ item.Address.Country }}</td>
          <td>{{ item.Address.Pin }}</td>
          <td>{{ item.FathersDetails.FatherName.ffirstname }}</td>
          <td>{{ item.FathersDetails.FatherName.fmiddlename }}</td>
          <td>{{ item.FathersDetails.FatherName.flastname }}</td>
          <td>{{ item.FathersDetails.femail }}</td>
          <td>{{ item.FathersDetails.feq }}</td>
          <td>{{ item.FathersDetails.fprof }}</td>
          <td>{{ item.FathersDetails.fdesg }}</td>
          <td>{{ item.FathersDetails.fphone }}</td>
          <td>{{ item.MothersDetails.MotherName.mfirstname }}</td>
          <td>{{ item.MothersDetails.MotherName.mmiddlename }}</td>
          <td>{{ item.MothersDetails.MotherName.mlastname }}</td>
          <td>{{ item.MothersDetails.memail }}</td>
          <td>{{ item.MothersDetails.meq }}</td>
          <td>{{ item.MothersDetails.mprof }}</td>
          <td>{{ item.MothersDetails.mdesg }}</td>
          <td>{{ item.MothersDetails.mphone }}</td>

          <td colspan="2">
            <ul v-for="n in item.enumber" :key="n.relation">
              <li>{{ n.relation }} : {{ n.number }}</li>
            </ul>
          </td>

          <td>{{ item.refthrough }}</td>
          <td>{{ item.address }}</td>
          <td>{{ item.contact }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script>
import useVuelidate from '@vuelidate/core';
import { required, email } from '@vuelidate/validators';

const mustbe10digit = (value) => value.match('^((\\+91-?)|0)?[0-9]{10}$');

export default {
  name: 'app',
  setup() {
    return { v$: useVuelidate() };
  },
  data() {
    return {
      student: {
        Name: {
          firstName: '',
          middleName: '',
          lastName: '',
        },

        DOB: '',
        place_of_birth: '',
        first_language: '',
        Address: {
          City: '',
          State: '',
          Country: '',
          Pin: '',
        },
        FathersDetails: {
          FatherName: {
            ffirstname: '',
            flastname: '',
            fmiddlename: '',
          },
          femail: '',
          feq: '',
          fprof: '',
          fdesg: '',
          fphone: '',
        },
        MothersDetails: {
          MotherName: {
            mfirstname: '',
            mlastname: '',
            mmiddlename: '',
          },
          memail: '',
          meq: '',
          mprof: '',
          mdesg: '',
          mphone: '',
        },

        enumber: [
          {
            relation: '',
            number: '',
          },
        ],
        refthrough: '',
        address: '',
        contact: '',
      },
      allentries: [],
    };
  },
  validations() {
    return {
      student: {
        Name: {
          firstName: { required },
          middleName: { required },
          lastName: { required },
        },
        DOB: { required },
        FathersDetails: {
          FatherName: {
            ffirstname: { required },
          },
          femail: { email },
          fphone: { mustbe10digit },
        },
        MothersDetails: {
          MotherName: {
            mfirstname: { required },
          },
          memail: { email },
          mphone: { mustbe10digit },
        },
        contact: { required, mustbe10digit },
      },
    };
  },

  methods: {
    addenumber: function () {
    this.student.enumber.push({
        relation: '',
        number: '',
      });
    },

    async submitdata() {
      const isFormCorrect = await this.v$.$validate();

      if (!isFormCorrect) {
        alert('please fill all the required details');
        return;
      }

      let temp = JSON.stringify(this.student);

      this.allentries.push(temp);

      console.log(this.allentries);
    },
  },
};
</script>

<style>

</style>
