// Angular_React_Vue/Day2/Assignments/VueComponent/Source/src/App.vue
<template>
<div>
  <Header /> 
  <Section />
  <Footer />
</div>
</template>

<script>

import Footer from './components/Footer.vue'
import Section from './components/Section.vue'
import Header from './components/Header.vue'

export default {
  name: 'App',
  components: {
  Header,
  Section,
  Footer,
  }
}
</script>

<style>

</style>

// React/Day2/Assignment/Component/Source/src/App.js
import logo from './logo.svg';
import './App.css';
import Header from './components/Header.js';
import Section from './components/Section.js';
import Footer from './components/Footer.js';

function App() {
  return (
    <div className="App">
     <Header/>
     <Section/>
     <Footer/>
    </div>
  );
}

export default App;
